-- FABRICANTES
-- GRUPOS DE PRECIFICAÇÃO
-- CATEGORIAS
-- CIDADES/ESTADOS/PAISES




INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (1,null,null,8,'30/01/1980','M','7281-1080','11','Residencial','Curabitur@consequatlectussit.ca','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (2,null,null,2,'10/10/1998','M','7993-7889','15','Celular','mi.Aliquam@Proineget.net','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (11,null,null,6,'20/05/1998','F','3090-4464','80','Celular','mi@erat.com','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (12,null,null,1,'22/11/1998','M','1593-0115','11','Celular','sagittis.augue.eu@Phasellusfermentumconvallis.edu','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (21,null,null,2,'16/08/1980','M','1079-7274','15','Residencial','conubia.nostra@penatibuset.ca','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (22,null,null,3,'28/08/1998','M','2043-9099','2','Celular','ultrices.a.auctor@aliquetmolestie.co.uk','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (31,null,null,8,'28/06/1998','M','0344-3976','15','Celular','lobortis.augue.scelerisque@pretium.net','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (41,null,null,4,'15/10/1998','M','4610-1875','31','Celular','sollicitudin@gravidaAliquam.net','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (42,null,null,8,'11/05/1980','M','0174-9932','31','Residencial','tristique@arcuiaculis.edu','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (51,null,null,7,'10/06/1998','M','6555-7786','80','Celular','rutrum.magna.Cras@gravidaAliquamtincidunt.co.uk','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (52,null,null,4,'20/01/1980','M','5073-0277','11','Residencial','ante.lectus.convallis@justoProin.edu','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (61,null,null,6,'03/05/1998','F','2211-4607','11','Celular','Proin.velit@natoquepenatibus.co.uk','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (62,null,null,6,'05/05/1980','M','7719-9204','11','Residencial','mollis@id.net','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (71,null,null,8,'25/01/1998','M','5096-2390','31','Residencial','interdum.feugiat@volutpat.co.uk','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (72,null,null,9,'28/07/1980','F','2261-9407','80','Celular','convallis@vitaedolor.edu','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (81,null,null,7,'16/08/1980','M','7726-8039','15','Celular','amet@gravidasitamet.ca','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (82,null,null,1,'30/06/1998','M','4886-0630','15','Residencial','Donec@hendrerit.org','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (91,null,null,9,'18/11/1998','F','9003-5314','31','Celular','urna.convallis@leo.ca','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (92,null,null,3,'28/11/1998','F','1725-9737','31','Residencial','Phasellus.ornare@nectempus.co.uk','Aa@123456');
INSERT INTO "clientes" (cli_id,cli_cpm_id,cli_crt_id,cli_cpf,cli_dt_nasc,cli_genero,cli_telefone_num,cli_telefone_ddd,cli_telefone_tp,cli_email,cli_senha) VALUES (32,null,null,10,'08/10/1980','F','1070-4712','80','Residencial','Nam.nulla.magna@ante.net','Aa@123456');